### ISSUE TITLE
Tracking issue: Auto Routines for WARP

### ISSUE THREAD

**Issue by spacey-sooty** [CurtinFRC/2024-Offseason#26]
We want to be able to achieve a certain set of auto routines for WARP, this list needs to be decided then steps taken towards achieving it. 
Our goal is a 6 note auto assuming no partners.

- [ ] close 4 note
- [ ] 2 far 1 close left (4 note)
- [ ] 2 far 1 close right (4 note)
- [ ] close center 5 note
- [ ] close left 5 note
- [ ] close right 5 note
- [ ] far left 5 note
- [ ] far right 5 note
- [ ] full 6 note

There are a variety of steps required before these can be easily and reliably be achieved.
- [x] #27
- [x] #24
- [ ] #17 
- [ ] #30
- [x] #66
